## Latihan PK 31 mei 2024

In [7]:
#perkalian matrix array

import numpy as np

A = np.array([16, 11, 24])
B = np.array([22, 17, 49])
C = np.array([16, 10, 20])

perkalian = A * B * C
print(perkalian)

[ 5632  1870 23520]


In [6]:
#pengurangan matrix array

import numpy as np

A = np.array([16, 11, 24])
B = np.array([22, 17, 49])
C = np.array([16, 10, 20])

pengurangan = A - B - C
print(pengurangan)

[-22 -16 -45]


In [11]:
#transpose matrix array

import numpy as np

A = np.array([[16, 11, 24],[22, 17, 49],[16, 10, 20]])

transpose_A = np.transpose(A)
print(transpose_A)

[[16 22 16]
 [11 17 10]
 [24 49 20]]


In [13]:
#invers matrix array

import numpy as np

A = np.array([[16, 11, 24],[22, 17, 49],[16, 10, 20]])

inverse_A = np.linalg.inv(A)
print("\nInvers matrix A:")
print(inverse_A)



Invers matrix A:
[[-1.10294118  0.14705882  0.96323529]
 [ 2.52941176 -0.47058824 -1.88235294]
 [-0.38235294  0.11764706  0.22058824]]


In [14]:
#determinan matrix array

import numpy as np

A = np.array([[16, 11, 24],[22, 17, 49],[16, 10, 20]])

determinant_A = np.linalg.det(A)
print("Determinant dari matrix A:", determinant_A)


Determinant dari matrix A: 136.00000000000006
